"""added description to FormMeta

Revision ID: 1967d5cd4d7b
Revises: 47a39bab0bc4
Create Date: 2015-03-10 11:40:27.201160

"""

# revision identifiers, used by Alembic.
revision = '1967d5cd4d7b'
down_revision = '47a39bab0bc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ee657574d65f_open_gov_hack_night')
    op.add_column('form_meta', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_meta', 'description')
    op.create_table('ee657574d65f_open_gov_hack_night',
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('transcriber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_name_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('first_name_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'ee657574d65f_open_gov_hack_night_pkey')
    )
    ### end Alembic commands ###
