"""added description to FormMeta

Revision ID: 1967d5cd4d7b
Revises: 47a39bab0bc4
Create Date: 2015-03-10 11:40:27.201160

"""

# revision identifiers, used by Alembic.
revision = '1967d5cd4d7b'
down_revision = '47a39bab0bc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_meta', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_meta', 'description')
    ### end Alembic commands ###
