"""Adding default to image view count

Revision ID: 1b6cbddb3fd5
Revises: 
Create Date: 2015-02-25 09:19:45.194075

"""

# revision identifiers, used by Alembic.
revision = '1b6cbddb3fd5'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a889ee8fae84_presidential_election')
    op.drop_table('2e55c8553842_honduras_elections')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('2e55c8553842_honduras_elections',
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('transcriber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"2e55c8553842_honduras_elections_id_seq"\'::regclass)'), nullable=False),
    sa.Column('departamento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('la_alianza', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('democracia_cristiana', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'2e55c8553842_honduras_elections_pkey')
    )
    op.create_table('a889ee8fae84_presidential_election',
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('transcriber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('boolean', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('party_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('municipio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('departamento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'a889ee8fae84_presidential_election_pkey')
    )
    ### end Alembic commands ###
