"""Adding default to image view count

Revision ID: 1b6cbddb3fd5
Revises: 
Create Date: 2015-02-25 09:19:45.194075

"""

# revision identifiers, used by Alembic.
revision = '1b6cbddb3fd5'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
