"""Add work table

Revision ID: 215ce54423be
Revises: eea85a81b4e
Create Date: 2016-10-26 16:46:39.845282

"""

# revision identifiers, used by Alembic.
revision = '215ce54423be'
down_revision = 'eea85a81b4e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
