"""add is_complete to ImageTaskAssignment

Revision ID: 30838544ae51
Revises: 464ef2b94175
Create Date: 2015-06-05 20:06:15.131836

"""

# revision identifiers, used by Alembic.
revision = '30838544ae51'
down_revision = '464ef2b94175'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_meta', 'final_table_name')
    op.add_column('image_task_assignment', sa.Column('is_complete', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_task_assignment', 'is_complete')
    op.add_column('form_meta', sa.Column('final_table_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
