"""Add election name

Revision ID: 31d5082abc8
Revises: 31efdc0f241
Create Date: 2017-10-19 13:33:00.055487

"""

# revision identifiers, used by Alembic.
revision = '31d5082abc8'
down_revision = '31efdc0f241'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_cloud_image')
    op.add_column('image', sa.Column('election_name', sa.String(), nullable=True))
    op.drop_column('image', 'bucket')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('image', 'election_name')
    op.create_table('document_cloud_image',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fetch_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dc_project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dc_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hierarchy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_page_url', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_cloud_image_pkey')
    )
    ### end Alembic commands ###
