"""S3 mods

Revision ID: 31efdc0f241
Revises: 34d9a051aef
Create Date: 2017-10-19 10:40:24.795602

"""

# revision identifiers, used by Alembic.
revision = '31efdc0f241'
down_revision = '34d9a051aef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('fetch_url', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('hierarchy', postgresql.JSONB(), nullable=True),
    sa.Column('is_page_url', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute('''
        ALTER TABLE image_task_assignment
        ADD COLUMN legacy_id VARCHAR
    ''')

    op.execute('''
        UPDATE image_task_assignment SET
          legacy_id = image_id
    ''')

    op.execute('''
        UPDATE image_task_assignment SET
          image_id = NULL
    ''')

    op.execute('''
        ALTER TABLE image_task_assignment
        DROP CONSTRAINT image_task_assignment_image_id_fkey
    ''')

    op.execute('''
        ALTER TABLE image_task_assignment
        ALTER COLUMN image_id TYPE UUID USING image_id::UUID
    ''')

    op.execute('''
        ALTER TABLE image_task_assignment
        ADD CONSTRAINT image_task_assignment_image_id_fkey
        FOREIGN KEY (image_id) REFERENCES image(id)
    ''')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE image_task_assignment
        DROP CONSTRAINT image_task_assignment_image_id_fkey
    ''')
    op.execute('''
        ALTER TABLE image_task_assignment
        ADD CONSTRAINT image_task_assignment_image_id_fkey
        FOREIGN KEY (image_id) REFERENCES document_cloud_image(dc_id)
    ''')
    op.drop_table('image')
    ### end Alembic commands ###
