"""initial

Revision ID: 34d9a051aef
Revises:
Create Date: 2017-10-19 10:33:45.296941

"""

# revision identifiers, used by Alembic.
revision = '34d9a051aef'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_cloud_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('fetch_url', sa.String(), nullable=True),
    sa.Column('dc_project', sa.String(), nullable=True),
    sa.Column('dc_id', sa.String(), nullable=True),
    sa.Column('hierarchy', sa.String(), nullable=True),
    sa.Column('is_page_url', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id')
    )
    op.create_table('ndi_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ndi_role',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_table',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('return_value', postgresql.JSONB(), nullable=True),
    sa.Column('work_value', sa.LargeBinary(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('cleared', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ndi_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ndi_user.id'], )
    )
    op.create_table('form_meta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_image', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('task_group_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_count', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dc_project', sa.String(), nullable=True),
    sa.Column('dc_filter', sa.Text(), nullable=True),
    sa.Column('split_image', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_group_id'], ['task_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_task_assignment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('checkout_expire', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form_meta.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['document_cloud_image.dc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_section',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form_meta.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['form_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_field')
    op.drop_table('form_section')
    op.drop_table('image_task_assignment')
    op.drop_table('form_meta')
    op.drop_table('roles_users')
    op.drop_table('work_table')
    op.drop_table('ndi_role')
    op.drop_table('ndi_user')
    op.drop_table('document_cloud_image')
    op.drop_table('task_group')
    ### end Alembic commands ###
