"""Adding confirmed_at to user table

Revision ID: 3a3f39b6fcd2
Revises: 5ab675eb9ee
Create Date: 2015-04-10 10:44:42.114648

"""

# revision identifiers, used by Alembic.
revision = '3a3f39b6fcd2'
down_revision = '5ab675eb9ee'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndi_user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndi_user', 'confirmed_at')
    ### end Alembic commands ###
