"""idk

Revision ID: 3d53f326be95
Revises: 4737db3bc9c2
Create Date: 2015-06-12 16:46:02.282471

"""

# revision identifiers, used by Alembic.
revision = '3d53f326be95'
down_revision = '4737db3bc9c2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_cloud_image', sa.Column('dc_id', sa.String(), nullable=True))
    op.add_column('document_cloud_image', sa.Column('dc_project', sa.String(), nullable=True))
    op.add_column('document_cloud_image', sa.Column('hierarchy', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_cloud_image', 'hierarchy')
    op.drop_column('document_cloud_image', 'dc_project')
    op.drop_column('document_cloud_image', 'dc_id')
    ### end Alembic commands ###
