"""add flags to documentcloudimage

Revision ID: 3e96ae10921f
Revises: 3d53f326be95
Create Date: 2015-06-14 20:28:51.904737

"""

# revision identifiers, used by Alembic.
revision = '3e96ae10921f'
down_revision = '3d53f326be95'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_cloud_image', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('document_cloud_image', sa.Column('is_page_url', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_cloud_image', 'is_page_url')
    op.drop_column('document_cloud_image', 'is_current')
    ### end Alembic commands ###
