"""Add another election name

Revision ID: 3fec283e512
Revises: 3b5bf4bf1e3
Create Date: 2017-10-20 09:07:58.619962

"""

# revision identifiers, used by Alembic.
revision = '3fec283e512'
down_revision = '3b5bf4bf1e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_meta', sa.Column('election_name', sa.String(), nullable=True))
    op.add_column('form_meta', sa.Column('hierarchy_filter', postgresql.JSONB(), nullable=True))
    op.drop_column('form_meta', 'dc_filter')
    op.drop_column('form_meta', 'dc_project')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_meta', sa.Column('dc_project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('form_meta', sa.Column('dc_filter', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('form_meta', 'hierarchy_filter')
    op.drop_column('form_meta', 'election_name')
    ### end Alembic commands ###
