"""removing image table, allow for many-to-many between images and tasks

Revision ID: 464ef2b94175
Revises: 4a7558f55529
Create Date: 2015-06-02 13:47:15.575141

"""

# revision identifiers, used by Alembic.
revision = '464ef2b94175'
down_revision = '4a7558f55529'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
