"""adding document cloud info to image table

Revision ID: 4737db3bc9c2
Revises: 51949e169325
Create Date: 2015-06-12 15:29:17.732990

"""

# revision identifiers, used by Alembic.
revision = '4737db3bc9c2'
down_revision = '51949e169325'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
