"""Adding status

Revision ID: 47a39bab0bc4
Revises: 1b6cbddb3fd5
Create Date: 2015-03-09 16:41:05.883645

"""

# revision identifiers, used by Alembic.
revision = '47a39bab0bc4'
down_revision = '1b6cbddb3fd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_field', sa.Column('status', sa.String(), nullable=True))
    op.add_column('form_meta', sa.Column('status', sa.String(), nullable=True))
    op.add_column('form_section', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_section', 'status')
    op.drop_column('form_meta', 'status')
    op.drop_column('form_field', 'status')
    ### end Alembic commands ###
