"""Adding Task Group

Revision ID: 49461329b9b
Revises: 47a39bab0bc4
Create Date: 2015-03-10 12:15:10.782659

"""

# revision identifiers, used by Alembic.
revision = '49461329b9b'
down_revision = '47a39bab0bc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('form_meta', sa.Column('task_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form_meta', 'task_group', ['task_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_meta', type_='foreignkey')
    op.drop_column('form_meta', 'task_group_id')
    op.drop_table('task_group')
    ### end Alembic commands ###
