"""Adding Task Group

Revision ID: 49461329b9b
Revises: 47a39bab0bc4
Create Date: 2015-03-10 12:15:10.782659

"""

# revision identifiers, used by Alembic.
revision = '49461329b9b'
down_revision = '47a39bab0bc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('c6b08c3a2aa9_new_columbia')
    op.add_column('form_meta', sa.Column('task_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form_meta', 'task_group', ['task_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_meta', type_='foreignkey')
    op.drop_column('form_meta', 'task_group_id')
    op.create_table('c6b08c3a2aa9_new_columbia',
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('transcriber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('municipality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('municipality_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('municipality_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department_id_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('department_id_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('juan_manuel_santos_calderon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('juan_manuel_santos_calderon_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('juan_manuel_santos_calderon_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('oscar_ivan_zuluaga', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oscar_ivan_zuluaga_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('oscar_ivan_zuluaga_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department_blank', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('department_not_legible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'c6b08c3a2aa9_new_columbia_pkey')
    )
    op.drop_table('task_group')
    ### end Alembic commands ###
