"""removing image table, allow for many-to-many between images and tasks

Revision ID: 4a7558f55529
Revises: 3a3f39b6fcd2
Create Date: 2015-06-02 13:35:50.258194

"""

# revision identifiers, used by Alembic.
revision = '4a7558f55529'
down_revision = '3a3f39b6fcd2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
