"""Add unique constraint

Revision ID: 4b92e3a80f5
Revises: 57dd92c709b
Create Date: 2017-02-23 10:02:36.487319

"""

# revision identifiers, used by Alembic.
revision = '4b92e3a80f5'
down_revision = '57dd92c709b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
