"""Add indexes

Revision ID: 4bad110292d
Revises: 3b5bf4bf1e3
Create Date: 2017-09-14 11:13:41.275267

"""

# revision identifiers, used by Alembic.
revision = '4bad110292d'
down_revision = '3b5bf4bf1e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        CREATE INDEX project_name_index
        ON document_cloud_image (dc_project)
    ''')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
