"""add checkout expire to image

Revision ID: 5ab675eb9ee
Revises: 285cfcb83a68
Create Date: 2015-04-08 12:19:35.650922

"""

# revision identifiers, used by Alembic.
revision = '5ab675eb9ee'
down_revision = '285cfcb83a68'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('checkout_expire', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'checkout_expire')
    ### end Alembic commands ###
